# Specify a base image

FROM node:alpine

# Working directory 

WORKDIR /usr/app

# Copying the application file to container and Installing dependencies

COPY ./package.json ./
RUN npm install
COPY ./index.js ./

# Default command to execute

CMD ["npm" , "start"]
 