# Specify a base image

FROM node:alpine

# Working directory 

WORKDIR /usr/app

# Copying the application file to container 

COPY . .

# Installing dependencies

RUN npm install

# Default command to execute

CMD ["npm" , "start"]
 